title: DONGChuan - Chuan's Website
name: DONGChuan
email: dongchuan55@gmail.com
description: Chuan's Website
keywords: 董川
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, JSP]
skill_web_keywords: [HTML, CSS, Javascript, Jquery, ajax, Angularjs, Nodejs, MongoDB, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]

timezone: PRC
encoding: "utf-8"

url: http://dongchuan.github.io
baseurl:  "/"
domain:
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/DONGChuan/DONGChuan.github.io

# Build settings
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  - jekyll-html-pipeline
  - jekyll-paginate

analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

popular_repos: ['GradleUserGuide','YummyWakeUp', 'Java-BackGammon', 'Java-Interview-Question', 'PoetrySearch']
contribute_repos: ['UFreedom/YummyTime', 'UFreedom/CountDownTextView']
